### ISSUE TITLE
Manter Usuario - Formulário de Cadastro de Acesso

### ISSUE THREAD

**Issue by JoseLuizJunior** [PedroCorreiaSena/SISREC#14]
Não esta gravando os seguintes campos do formulário:

Data de Nascimento, DDD telefone principal, Telefone Principal, DDD telefone alternativo, Telefone alternativo e Casa

**Comment by JoseLuizJunior** [comment]
Não possui a opção de escolher o perfil do usuário, se é associado ou se é administrador. Incluir está opção.

**Comment by Skailander** [comment]
O botão Alterar Cadastro deve possuir o nome Cadastrar Usuário.

**Comment by felipeslino** [comment]
Retira meu email do github
Em 01/06/2016 16:52, "Júnior" notifications@github.com escreveu:
